---
driver:
  name: docker
driver_config:
  require_chef_omnibus: 11.16.4
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: ['spark::standalone']
